services:
  app:
    build: .
    container_name: myapp
    ports:
      - "8080:8080"
      - "50051:50051"
    stdin_open: true
    tty: true
    environment:
      - APP_CONFIG=/app/config/app_config.yaml
    volumes:
      - ./config:/app/config:ro
      - ./data:/app/data
      - ./logs:/app/logs
    depends_on:
      - postgres
      - redis
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

  postgres:
    image: postgres:17-alpine
    environment:
        - POSTGRES_USER=myuser
        - POSTGRES_PASSWORD=mypassword
    container_name: postgres
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    networks:
        - app-network

  migrate:
    image: migrate/migrate
    depends_on:
      - postgres
    volumes:
      - ./migrations:/migrations
    command: [
      "-path", "/migrations",
      "-database", "postgres://myuser:mypassword@postgres:5432/?sslmode=disable",
      "up"
    ]
    networks:
      - app-network

volumes:
  redis_data:
  postgres_data:

networks:
  app-network:
