// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: dumpd/v1/dumpd.proto

package dumpd_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Item) Reset() {
	*x = Item{}
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_dumpd_v1_dumpd_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Item) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type GetItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemRequest) Reset() {
	*x = GetItemRequest{}
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemRequest) ProtoMessage() {}

func (x *GetItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemRequest.ProtoReflect.Descriptor instead.
func (*GetItemRequest) Descriptor() ([]byte, []int) {
	return file_dumpd_v1_dumpd_proto_rawDescGZIP(), []int{1}
}

func (x *GetItemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetItemResponse) Reset() {
	*x = GetItemResponse{}
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetItemResponse) ProtoMessage() {}

func (x *GetItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetItemResponse.ProtoReflect.Descriptor instead.
func (*GetItemResponse) Descriptor() ([]byte, []int) {
	return file_dumpd_v1_dumpd_proto_rawDescGZIP(), []int{2}
}

func (x *GetItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemRequest) Reset() {
	*x = CreateItemRequest{}
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemRequest) ProtoMessage() {}

func (x *CreateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemRequest.ProtoReflect.Descriptor instead.
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return file_dumpd_v1_dumpd_proto_rawDescGZIP(), []int{3}
}

func (x *CreateItemRequest) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type CreateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateItemResponse) Reset() {
	*x = CreateItemResponse{}
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateItemResponse) ProtoMessage() {}

func (x *CreateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateItemResponse.ProtoReflect.Descriptor instead.
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return file_dumpd_v1_dumpd_proto_rawDescGZIP(), []int{4}
}

func (x *CreateItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemRequest) Reset() {
	*x = UpdateItemRequest{}
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemRequest) ProtoMessage() {}

func (x *UpdateItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return file_dumpd_v1_dumpd_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateItemRequest) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *Item                  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateItemResponse) Reset() {
	*x = UpdateItemResponse{}
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateItemResponse) ProtoMessage() {}

func (x *UpdateItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateItemResponse) Descriptor() ([]byte, []int) {
	return file_dumpd_v1_dumpd_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateItemResponse) GetItem() *Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type DeleteItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemRequest) Reset() {
	*x = DeleteItemRequest{}
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemRequest) ProtoMessage() {}

func (x *DeleteItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return file_dumpd_v1_dumpd_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteItemRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteItemResponse) Reset() {
	*x = DeleteItemResponse{}
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteItemResponse) ProtoMessage() {}

func (x *DeleteItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return file_dumpd_v1_dumpd_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteItemResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type GetAllItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllItemsRequest) Reset() {
	*x = GetAllItemsRequest{}
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItemsRequest) ProtoMessage() {}

func (x *GetAllItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllItemsRequest.ProtoReflect.Descriptor instead.
func (*GetAllItemsRequest) Descriptor() ([]byte, []int) {
	return file_dumpd_v1_dumpd_proto_rawDescGZIP(), []int{9}
}

func (x *GetAllItemsRequest) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type GetAllItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Item                `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllItemsResponse) Reset() {
	*x = GetAllItemsResponse{}
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllItemsResponse) ProtoMessage() {}

func (x *GetAllItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dumpd_v1_dumpd_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllItemsResponse.ProtoReflect.Descriptor instead.
func (*GetAllItemsResponse) Descriptor() ([]byte, []int) {
	return file_dumpd_v1_dumpd_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllItemsResponse) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_dumpd_v1_dumpd_proto protoreflect.FileDescriptor

const file_dumpd_v1_dumpd_proto_rawDesc = "" +
	"\n" +
	"\x14dumpd/v1/dumpd.proto\x12\bdumpd.v1\x1a\x1bgoogle/protobuf/empty.proto\"@\n" +
	"\x04Item\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\" \n" +
	"\x0eGetItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"5\n" +
	"\x0fGetItemResponse\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.dumpd.v1.ItemR\x04item\"7\n" +
	"\x11CreateItemRequest\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.dumpd.v1.ItemR\x04item\"8\n" +
	"\x12CreateItemResponse\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.dumpd.v1.ItemR\x04item\"7\n" +
	"\x11UpdateItemRequest\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.dumpd.v1.ItemR\x04item\"8\n" +
	"\x12UpdateItemResponse\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.dumpd.v1.ItemR\x04item\"#\n" +
	"\x11DeleteItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"B\n" +
	"\x12DeleteItemResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"B\n" +
	"\x12GetAllItemsRequest\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\";\n" +
	"\x13GetAllItemsResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.dumpd.v1.ItemR\x05items2\xf5\x02\n" +
	"\fDumpdService\x12>\n" +
	"\aGetItem\x12\x18.dumpd.v1.GetItemRequest\x1a\x19.dumpd.v1.GetItemResponse\x12G\n" +
	"\n" +
	"CreateItem\x12\x1b.dumpd.v1.CreateItemRequest\x1a\x1c.dumpd.v1.CreateItemResponse\x12G\n" +
	"\n" +
	"UpdateItem\x12\x1b.dumpd.v1.UpdateItemRequest\x1a\x1c.dumpd.v1.UpdateItemResponse\x12G\n" +
	"\n" +
	"DeleteItem\x12\x1b.dumpd.v1.DeleteItemRequest\x1a\x1c.dumpd.v1.DeleteItemResponse\x12J\n" +
	"\vGetAllItems\x12\x1c.dumpd.v1.GetAllItemsRequest\x1a\x1d.dumpd.v1.GetAllItemsResponseB4Z2github.com/folivorra/dumpd/proto/dumpd/v1;dumpd_v1b\x06proto3"

var (
	file_dumpd_v1_dumpd_proto_rawDescOnce sync.Once
	file_dumpd_v1_dumpd_proto_rawDescData []byte
)

func file_dumpd_v1_dumpd_proto_rawDescGZIP() []byte {
	file_dumpd_v1_dumpd_proto_rawDescOnce.Do(func() {
		file_dumpd_v1_dumpd_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dumpd_v1_dumpd_proto_rawDesc), len(file_dumpd_v1_dumpd_proto_rawDesc)))
	})
	return file_dumpd_v1_dumpd_proto_rawDescData
}

var file_dumpd_v1_dumpd_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_dumpd_v1_dumpd_proto_goTypes = []any{
	(*Item)(nil),                // 0: dumpd.v1.Item
	(*GetItemRequest)(nil),      // 1: dumpd.v1.GetItemRequest
	(*GetItemResponse)(nil),     // 2: dumpd.v1.GetItemResponse
	(*CreateItemRequest)(nil),   // 3: dumpd.v1.CreateItemRequest
	(*CreateItemResponse)(nil),  // 4: dumpd.v1.CreateItemResponse
	(*UpdateItemRequest)(nil),   // 5: dumpd.v1.UpdateItemRequest
	(*UpdateItemResponse)(nil),  // 6: dumpd.v1.UpdateItemResponse
	(*DeleteItemRequest)(nil),   // 7: dumpd.v1.DeleteItemRequest
	(*DeleteItemResponse)(nil),  // 8: dumpd.v1.DeleteItemResponse
	(*GetAllItemsRequest)(nil),  // 9: dumpd.v1.GetAllItemsRequest
	(*GetAllItemsResponse)(nil), // 10: dumpd.v1.GetAllItemsResponse
	(*emptypb.Empty)(nil),       // 11: google.protobuf.Empty
}
var file_dumpd_v1_dumpd_proto_depIdxs = []int32{
	0,  // 0: dumpd.v1.GetItemResponse.item:type_name -> dumpd.v1.Item
	0,  // 1: dumpd.v1.CreateItemRequest.item:type_name -> dumpd.v1.Item
	0,  // 2: dumpd.v1.CreateItemResponse.item:type_name -> dumpd.v1.Item
	0,  // 3: dumpd.v1.UpdateItemRequest.item:type_name -> dumpd.v1.Item
	0,  // 4: dumpd.v1.UpdateItemResponse.item:type_name -> dumpd.v1.Item
	11, // 5: dumpd.v1.DeleteItemResponse.empty:type_name -> google.protobuf.Empty
	11, // 6: dumpd.v1.GetAllItemsRequest.empty:type_name -> google.protobuf.Empty
	0,  // 7: dumpd.v1.GetAllItemsResponse.items:type_name -> dumpd.v1.Item
	1,  // 8: dumpd.v1.DumpdService.GetItem:input_type -> dumpd.v1.GetItemRequest
	3,  // 9: dumpd.v1.DumpdService.CreateItem:input_type -> dumpd.v1.CreateItemRequest
	5,  // 10: dumpd.v1.DumpdService.UpdateItem:input_type -> dumpd.v1.UpdateItemRequest
	7,  // 11: dumpd.v1.DumpdService.DeleteItem:input_type -> dumpd.v1.DeleteItemRequest
	9,  // 12: dumpd.v1.DumpdService.GetAllItems:input_type -> dumpd.v1.GetAllItemsRequest
	2,  // 13: dumpd.v1.DumpdService.GetItem:output_type -> dumpd.v1.GetItemResponse
	4,  // 14: dumpd.v1.DumpdService.CreateItem:output_type -> dumpd.v1.CreateItemResponse
	6,  // 15: dumpd.v1.DumpdService.UpdateItem:output_type -> dumpd.v1.UpdateItemResponse
	8,  // 16: dumpd.v1.DumpdService.DeleteItem:output_type -> dumpd.v1.DeleteItemResponse
	10, // 17: dumpd.v1.DumpdService.GetAllItems:output_type -> dumpd.v1.GetAllItemsResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_dumpd_v1_dumpd_proto_init() }
func file_dumpd_v1_dumpd_proto_init() {
	if File_dumpd_v1_dumpd_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dumpd_v1_dumpd_proto_rawDesc), len(file_dumpd_v1_dumpd_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dumpd_v1_dumpd_proto_goTypes,
		DependencyIndexes: file_dumpd_v1_dumpd_proto_depIdxs,
		MessageInfos:      file_dumpd_v1_dumpd_proto_msgTypes,
	}.Build()
	File_dumpd_v1_dumpd_proto = out.File
	file_dumpd_v1_dumpd_proto_goTypes = nil
	file_dumpd_v1_dumpd_proto_depIdxs = nil
}
